package game

const ( // iota is reset to 0
	BASIC             = 0
	MULTIPLY_WORD_2   = 1
	MULTIPLY_WORD_3   = 2
	MULTIPLY_LETTER_2 = 3
	MULTIPLY_LETTER_3 = 4
)

func GetLetterPointsTable() map[string]int {
	return map[string]int{
		"a": 1,
		"á": 2,
		"b": 2,
		"c": 3,
		"č": 4,

		"d": 2,
		"ď": 8,
		"e": 1,
		"é": 5,
		"ě": 5,

		"f":  8,
		"g":  8,
		"h":  3,
		"ch": 4,
		"i":  1,

		"í": 2,
		"j": 2,
		"k": 1,
		"l": 1,
		"m": 2,

		"n": 1,
		"ň": 6,
		"o": 1,
		"ó": 10,
		"p": 1,

		"r": 1,
		"ř": 4,
		"s": 1,
		"š": 3,
		"t": 1,

		"ť": 6,
		"u": 2,
		"ů": 5,
		"ú": 6,
		"v": 1,

		"x": 10,
		"y": 1,
		"ý": 4,
		"z": 3,
		"ž": 4,
	}
}

func GetDeskTileTypes() [15][15]int {
	return [15][15]int{
		{MULTIPLY_WORD_2, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, MULTIPLY_WORD_3},
		{BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC},
		{BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC},
		{MULTIPLY_LETTER_2, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, MULTIPLY_LETTER_2},
		{BASIC, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, BASIC, BASIC, MULTIPLY_WORD_2},
		{BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC},
		{BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC},

		{MULTIPLY_WORD_3, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, BASIC, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, MULTIPLY_WORD_2},

		{BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC},
		{BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC},
		{BASIC, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, BASIC, BASIC, MULTIPLY_WORD_2},
		{MULTIPLY_LETTER_2, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, MULTIPLY_LETTER_2},
		{BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC},
		{BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_3, BASIC, BASIC, BASIC, MULTIPLY_WORD_2, BASIC},
		{MULTIPLY_WORD_2, BASIC, BASIC, MULTIPLY_WORD_2, BASIC, BASIC, BASIC, MULTIPLY_WORD_3, BASIC, BASIC, BASIC, MULTIPLY_LETTER_2, BASIC, BASIC, MULTIPLY_WORD_3},
	}
}
